"""
Initializer —— 项目初始化器

基于 Anthropic 文章的设计：
- 第一次收到需求时运行
- 创建 init.sh 启动脚本
- 创建 feature_list.json
- 初始化 git 仓库
"""

from pathlib import Path
from typing import Optional

from config import OUTPUT_DIR
from feature_list import FeatureList


def create_init_script(work_dir: Optional[str] = None) -> str:
    """
    创建 init.sh 启动脚本
    返回脚本路径
    """
    work_path = Path(work_dir) if work_dir else OUTPUT_DIR
    work_path.mkdir(parents=True, exist_ok=True)

    script = work_path / "init.sh"
    script.write_text("""#!/bin/bash
# MeowDev 项目启动脚本
# 由猫猫团队自动生成

set -e

echo "🐱 MeowDev 初始化..."

# 检查 Python
if ! command -v python3 &> /dev/null; then
    echo "❌ 需要安装 Python 3"
    exit 1
fi

# 创建虚拟环境（如果不存在）
if [ ! -d ".venv" ]; then
    echo "📦 创建虚拟环境..."
    python3 -m venv .venv
fi

# 激活虚拟环境
source .venv/bin/activate

# 安装依赖（如果有 requirements.txt）
if [ -f "requirements.txt" ]; then
    echo "📥 安装依赖..."
    pip install -q -r requirements.txt
fi

echo "✅ 初始化完成！"
echo ""
echo "运行项目："
echo "  python app.py"
echo ""
""", encoding="utf-8")

    script.chmod(0o755)
    return str(script)


def create_readme(requirement: str, work_dir: Optional[str] = None) -> str:
    """创建 README.md"""
    work_path = Path(work_dir) if work_dir else OUTPUT_DIR
    work_path.mkdir(parents=True, exist_ok=True)

    content = f"""# MeowDev 项目

> 由三只猫猫（Arch酱、Stack喵、Pixel咪）协作生成

## 需求

{requirement}

## 运行

```bash
./init.sh
python app.py
```

## 功能列表

参见 `feature_list.json`

## 进度记录

参见 `progress.md`

---
*Generated by MeowDev Team*
"""
    readme_path = work_path / "README.md"
    readme_path.write_text(content, encoding="utf-8")
    return str(readme_path)


async def initialize_project(requirement: str, work_dir: Optional[str] = None) -> dict:
    """
    初始化项目（由 Initializer Agent 调用）

    返回创建的文件列表
    """
    work_path = Path(work_dir) if work_dir else OUTPUT_DIR
    work_path.mkdir(parents=True, exist_ok=True)

    created_files = []

    # 1. 创建 init.sh
    init_sh = create_init_script(work_dir)
    created_files.append(init_sh)

    # 2. 创建 README.md
    readme = create_readme(requirement, work_dir)
    created_files.append(readme)

    # 3. 初始化空的 feature_list.json（由 Arch酱 填充）
    fl = FeatureList(work_dir)
    fl._save()  # 创建空文件
    created_files.append(str(fl.file_path))

    # 4. 初始化 progress.md
    from progress import Progress
    prog = Progress(work_dir)
    prog.clear()
    prog.append(f"项目初始化\n需求: {requirement}", "Initializer")
    created_files.append(str(prog.file_path))

    return {
        "work_dir": str(work_path),
        "files": created_files,
    }
